!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2.1.0.dev0+git20240712.afe4598)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitchar_test(f2pysetupfunc)
      use char_test, only : change_strings
      external f2pysetupfunc
      call f2pysetupfunc(change_strings)
      end subroutine f2pyinitchar_test


