/* File: charmodule.c
 * This file is auto-generated with f2py (version:2.1.0.dev0+git20240712.afe4598).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Wed Jul 17 17:49:46 2024
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *char_error;
static PyObject *char_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;
typedef char character;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(char_error,errstring);\
        /*goto capi_fail;*/\
    } else 

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = char_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************* change_strings *******************************/
static char doc_f2py_rout_char_char_test_change_strings[] = "\
change_strings(strings,out_strings,[n_strs])\n\nWrapper for ``change_strings``.\
\n\nParameters\n----------\n"
"strings : input rank-2 array('c') with bounds (2,n_strs)\n"
"out_strings : input rank-2 array('c') with bounds (2,n_strs)\n"
"\nOther Parameters\n----------------\n"
"n_strs : input int, optional\n    Default: shape(strings, 1)";
/*  */
static PyObject *f2py_rout_char_char_test_change_strings(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(character*,int*,character*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    character *strings = NULL;
    npy_intp strings_Dims[2] = {-1, -1};
    const int strings_Rank = 2;
    PyArrayObject *capi_strings_as_array = NULL;
    int capi_strings_intent = 0;
    PyObject *strings_capi = Py_None;
    int n_strs = 0;
    PyObject *n_strs_capi = Py_None;
    character *out_strings = NULL;
    npy_intp out_strings_Dims[2] = {-1, -1};
    const int out_strings_Rank = 2;
    PyArrayObject *capi_out_strings_as_array = NULL;
    int capi_out_strings_intent = 0;
    PyObject *out_strings_capi = Py_None;
    static char *capi_kwlist[] = {"strings","out_strings","n_strs",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|O:char.char_test.change_strings",\
        capi_kwlist,&strings_capi,&out_strings_capi,&n_strs_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable strings */
    strings_Dims[0]=2;
    capi_strings_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "char.char.char_test.change_strings: failed to create array from the 1st argument `strings`";
    capi_strings_as_array = ndarray_from_pyobj(  NPY_STRING,1,strings_Dims,strings_Rank,  capi_strings_intent,strings_capi,capi_errmess);
    if (capi_strings_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = char_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        strings = (character *)(PyArray_DATA(capi_strings_as_array));

    /* Processing variable n_strs */
    if (n_strs_capi == Py_None) n_strs = shape(strings, 1); else
        f2py_success = int_from_pyobj(&n_strs,n_strs_capi,"char.char_test.change_strings() 1st keyword (n_strs) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(strings, 1) == n_strs,"shape(strings, 1) == n_strs","1st keyword n_strs","change_strings:n_strs=%d",n_strs) {
    /* Processing variable out_strings */
    out_strings_Dims[0]=2,out_strings_Dims[1]=n_strs;
    capi_out_strings_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "char.char.char_test.change_strings: failed to create array from the 2nd argument `out_strings`";
    capi_out_strings_as_array = ndarray_from_pyobj(  NPY_STRING,1,out_strings_Dims,out_strings_Rank,  capi_out_strings_intent,out_strings_capi,capi_errmess);
    if (capi_out_strings_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = char_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        out_strings = (character *)(PyArray_DATA(capi_out_strings_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(strings,&n_strs,out_strings);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_out_strings_as_array!=out_strings_capi) {
        Py_XDECREF(capi_out_strings_as_array); }
    }  /* if (capi_out_strings_as_array == NULL) ... else of out_strings */
    /* End of cleaning variable out_strings */
    } /*CHECKSCALAR(shape(strings, 1) == n_strs)*/
    } /*if (f2py_success) of n_strs*/
    /* End of cleaning variable n_strs */
    if((PyObject *)capi_strings_as_array!=strings_capi) {
        Py_XDECREF(capi_strings_as_array); }
    }  /* if (capi_strings_as_array == NULL) ... else of strings */
    /* End of cleaning variable strings */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of change_strings ***************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_char_test_def[] = {
  {"change_strings",-1,{{-1}},0,0,NULL,(void *)f2py_rout_char_char_test_change_strings,doc_f2py_rout_char_char_test_change_strings},
  {NULL}
};

static void f2py_setup_char_test(char *change_strings) {
  int i_f2py=0;
  f2py_char_test_def[i_f2py++].data = change_strings;
}
extern void F_FUNC_US(f2pyinitchar_test,F2PYINITCHAR_TEST)(void (*)(char *));
static void f2py_init_char_test(void) {
  F_FUNC_US(f2pyinitchar_test,F2PYINITCHAR_TEST)(f2py_setup_char_test);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "char",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_char(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = char_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module char (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.1.0.dev0+git20240712.afe4598");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'char' is auto-generated with f2py (version:2.1.0.dev0+git20240712.afe4598).\nFunctions:\n"
"Fortran 90/95 modules:\n""  char_test --- change_strings()"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.1.0.dev0+git20240712.afe4598");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    char_error = PyErr_NewException ("char.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_char_error", char_error);
    Py_DECREF(char_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }

/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "char_test", PyFortranObject_New(f2py_char_test_def,f2py_init_char_test));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"char");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
